name: Deploy

on:
  # mainブランチにpushしたとき動く
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ChangeDirectory
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd ./web; npm ci
      - run: cd ./web; npm run build --if-present
        env:
          CI: false
      # ビルドした成果物を保存します。ビルド結果のパスがbuildではない場合は書き換えてください
      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: build
          path: ./web/build
  deploy:
    name: Deploy
    # もし前段のbuildが通らなかったらこっちは動作しません
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # ビルドした成果物を取り出します。pathの設定はuploadと合わせる必要があります
      - name: Download Artifact
        uses: actions/download-artifact@main
        with:
          name: build
          path: ./web/build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@main
        with:
          # 必要に応じて引数を足したりしてください
          args: deploy --only hosting
          working-directory: ./web
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
